// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtqtncuxurthqgcqxmru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0cXRuY3V4dXJ0aHFnY3F4bXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzUxMTksImV4cCI6MjA2NTQxMTExOX0.TPIlZuVdelEw7nt5MWlkUXgx8AIoDGDzhaZIhKdnyQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);